# Generated by Django 3.1.4 on 2021-01-11 15:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20201124_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'Đang ra'), (1, 'Đã hoàn thành'), (2, 'Tạm ngưng')], default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='home.book'),
        ),
        migrations.AddField(
            model_name='comment',
            name='time_pub',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 22, 38, 35, 886015)),
        ),
        migrations.AlterField(
            model_name='book',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 22, 38, 35, 881019)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.FileField(upload_to=home.models.Chapter.book_upload, validators=[home.validators.validate_ContentChapter]),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='time_pub',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 22, 38, 35, 884017)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
