# Generated by Django 3.1.4 on 2021-01-11 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210111_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 22, 39, 49, 517269)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='time_pub',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 22, 39, 49, 520274)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
