# Generated by Django 3.1.5 on 2021-01-13 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210111_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 9, 27, 13, 123901)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='time_pub',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 9, 27, 13, 124900)),
        ),
    ]
