# Generated by Django 3.1.5 on 2021-01-13 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210113_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 10, 4, 17, 674170)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='time_pub',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 10, 4, 17, 675170)),
        ),
    ]
