# Generated by Django 3.1.5 on 2021-01-13 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210113_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='click',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='Đang cập nhật'),
        ),
        migrations.AlterField(
            model_name='book',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 11, 14, 26, 565331)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='time_pub',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 11, 14, 26, 567331)),
        ),
    ]
