# Generated by Django 3.1.5 on 2021-01-13 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210113_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 16, 2, 20, 263070)),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='Đang cập nhật', max_length=2000),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='Đang cập nhật', max_length=2000),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='time_pub',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 16, 2, 20, 267068)),
        ),
    ]
