# Generated by Django 3.1.5 on 2021-01-14 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210114_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='userid',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='click',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 19, 11, 7, 52483)),
        ),
        migrations.AlterField(
            model_name='book',
            name='imageBook',
            field=models.ImageField(default='../static/images/book1.jpg', upload_to='image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='time_pub',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 19, 11, 7, 54482)),
        ),
    ]
